# creation rules are evaluated sequentially, the first match wins
creation_rules:
        # upon creation of a file that matches the pattern *dev.yaml,
        # KMS set A is used
        # eGOV Internal ------------------------------------------------------------------------------------------------------------- #
        - path_regex: environments/qa\-secrets\.yaml$
          kms: 'arn:aws:kms:ap-south-1:33756621284711:key/addasd-7b85-4469-8c9e-h5748rhf74h'
        - path_regex: environments/uat\-secrets\.yaml$
          kms: 'arn:aws:kms:ap-south-1:842676012585:key/6b82afe4-5b8e-4a2f-bd63-e8e0449b5953'
         # pgp: '58BE55DFE047D960AFF29E8891E02D93FD9F'           
